import './antd-style'
export { Agreement } from './agreement'
export { CodeVerification } from './codeVerification'
export { ImageVerification } from './imageVerification'
export { PhoneNumber } from './phoneNumber'
export { Submit } from './submit'
export { ErrorMessage } from './errorMessage'
export { Container } from './container'
