require('./index.css');
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./antd-style");
var agreement_1 = require("./agreement");
exports.Agreement = agreement_1.Agreement;
var codeVerification_1 = require("./codeVerification");
exports.CodeVerification = codeVerification_1.CodeVerification;
var imageVerification_1 = require("./imageVerification");
exports.ImageVerification = imageVerification_1.ImageVerification;
var phoneNumber_1 = require("./phoneNumber");
exports.PhoneNumber = phoneNumber_1.PhoneNumber;
var submit_1 = require("./submit");
exports.Submit = submit_1.Submit;
var errorMessage_1 = require("./errorMessage");
exports.ErrorMessage = errorMessage_1.ErrorMessage;
var container_1 = require("./container");
exports.Container = container_1.Container;
